//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "entrada")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub tipo_entrada_id: Uuid,
    pub compra_id: Uuid,
    #[sea_orm(unique)]
    pub qr_code: String,
    pub estado: Option<String>,
    pub fecha_uso: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::compra::Entity",
        from = "Column::CompraId",
        to = "super::compra::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Compra,
    #[sea_orm(
        belongs_to = "super::tipo_entrada::Entity",
        from = "Column::TipoEntradaId",
        to = "super::tipo_entrada::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TipoEntrada,
}

impl Related<super::compra::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Compra.def()
    }
}

impl Related<super::tipo_entrada::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TipoEntrada.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
