//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "evento")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub titulo: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub descripcion: Option<String>,
    pub fecha: Date,
    pub hora: Time,
    pub region: String,
    pub provincia: String,
    pub distrito: String,
    pub organizador_id: Uuid,
    pub categoria: String,
    pub aforo: i32,
    pub etiquetas: Option<String>,
    pub restriccion_edad: Option<String>,
    pub miniatura: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metodos_pago_aceptados: Option<Json>,
    pub estado: Option<String>,
    pub fecha_creacion: Option<DateTime>,
    pub fecha_actualizacion: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::compra::Entity")]
    Compra,
    #[sea_orm(has_many = "super::notificacion::Entity")]
    Notificacion,
    #[sea_orm(has_many = "super::tipo_entrada::Entity")]
    TipoEntrada,
    #[sea_orm(
        belongs_to = "super::usuario::Entity",
        from = "Column::OrganizadorId",
        to = "super::usuario::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Usuario,
}

impl Related<super::compra::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Compra.def()
    }
}

impl Related<super::notificacion::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notificacion.def()
    }
}

impl Related<super::tipo_entrada::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TipoEntrada.def()
    }
}

impl Related<super::usuario::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Usuario.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
