//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "notificacion")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub usuario_id: Uuid,
    pub tipo: String,
    pub titulo: String,
    #[sea_orm(column_type = "Text")]
    pub mensaje: String,
    pub leido: Option<bool>,
    pub fecha_creacion: Option<DateTime>,
    pub evento_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::evento::Entity",
        from = "Column::EventoId",
        to = "super::evento::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Evento,
    #[sea_orm(
        belongs_to = "super::usuario::Entity",
        from = "Column::UsuarioId",
        to = "super::usuario::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Usuario,
}

impl Related<super::evento::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Evento.def()
    }
}

impl Related<super::usuario::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Usuario.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
