//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub use super::compra::Entity as Compra;
pub use super::comprobante::Entity as Comprobante;
pub use super::entrada::Entity as Entrada;
pub use super::evento::Entity as Evento;
pub use super::notificacion::Entity as Notificacion;
pub use super::tipo_entrada::Entity as TipoEntrada;
pub use super::usuario::Entity as Usuario;
