//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "usuario")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub nombre: String,
    #[sea_orm(unique)]
    pub email: String,
    pub numero_cel: Option<String>,
    pub contraseña: String,
    pub estado: Option<String>,
    #[sea_orm(unique)]
    pub dni: String,
    pub fecha_registro: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::compra::Entity")]
    Compra,
    #[sea_orm(has_many = "super::evento::Entity")]
    Evento,
    #[sea_orm(has_many = "super::notificacion::Entity")]
    Notificacion,
}

impl Related<super::compra::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Compra.def()
    }
}

impl Related<super::evento::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Evento.def()
    }
}

impl Related<super::notificacion::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notificacion.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
