//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "comprobante")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub tipo: String,
    pub fecha_emision: Option<DateTime>,
    pub ruc_empresa: Option<String>,
    pub serie: String,
    pub correlativo: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub monto_total: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub igv: Option<Decimal>,
    pub archivo_pdf: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::compra::Entity")]
    Compra,
}

impl Related<super::compra::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Compra.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
