//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "compra")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub usuario_id: Uuid,
    pub evento_id: Uuid,
    pub comprobante_id: Option<Uuid>,
    pub fecha_compra: Option<DateTime>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub monto_total: Decimal,
    pub metodo_pago: String,
    pub estado_pago: Option<String>,
    pub codigo_operacion: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::comprobante::Entity",
        from = "Column::ComprobanteId",
        to = "super::comprobante::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Comprobante,
    #[sea_orm(has_many = "super::entrada::Entity")]
    Entrada,
    #[sea_orm(
        belongs_to = "super::evento::Entity",
        from = "Column::EventoId",
        to = "super::evento::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Evento,
    #[sea_orm(
        belongs_to = "super::usuario::Entity",
        from = "Column::UsuarioId",
        to = "super::usuario::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Usuario,
}

impl Related<super::comprobante::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Comprobante.def()
    }
}

impl Related<super::entrada::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Entrada.def()
    }
}

impl Related<super::evento::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Evento.def()
    }
}

impl Related<super::usuario::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Usuario.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
