//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub mod prelude;

pub mod compra;
pub mod comprobante;
pub mod entrada;
pub mod evento;
pub mod notificacion;
pub mod tipo_entrada;
pub mod usuario;
