//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tipo_entrada")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub evento_id: Uuid,
    pub nombre: String,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub precio: Decimal,
    pub max_por_compra: i32,
    pub cantidad_disponible: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub descripcion: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::entrada::Entity")]
    Entrada,
    #[sea_orm(
        belongs_to = "super::evento::Entity",
        from = "Column::EventoId",
        to = "super::evento::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Evento,
}

impl Related<super::entrada::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Entrada.def()
    }
}

impl Related<super::evento::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Evento.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
